#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'hello_types'

module Uzzu
  module Tutorial
    INT32CONSTANT = 9853

    MAPCONSTANT = {
      %q"hello" => %q"world",
      %q"goodnight" => %q"moon",
    }

  end
end
