/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"

#import "shared.h"

#import "hello.h"

@implementation Work

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
  self.num1 = 0;

#endif
  return self;
}

- (id) initWithNum1: (int32_t) num1 num2: (int32_t) num2 op: (int) op comment: (NSString *) comment
{
  self = [super init];
  __num1 = num1;
  __num1_isset = YES;
  __num2 = num2;
  __num2_isset = YES;
  __op = op;
  __op_isset = YES;
  __comment = [comment retain_stub];
  __comment_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"num1"])
  {
    __num1 = [decoder decodeInt32ForKey: @"num1"];
    __num1_isset = YES;
  }
  if ([decoder containsValueForKey: @"num2"])
  {
    __num2 = [decoder decodeInt32ForKey: @"num2"];
    __num2_isset = YES;
  }
  if ([decoder containsValueForKey: @"op"])
  {
    __op = [decoder decodeIntForKey: @"op"];
    __op_isset = YES;
  }
  if ([decoder containsValueForKey: @"comment"])
  {
    __comment = [[decoder decodeObjectForKey: @"comment"] retain_stub];
    __comment_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__num1_isset)
  {
    [encoder encodeInt32: __num1 forKey: @"num1"];
  }
  if (__num2_isset)
  {
    [encoder encodeInt32: __num2 forKey: @"num2"];
  }
  if (__op_isset)
  {
    [encoder encodeInt: __op forKey: @"op"];
  }
  if (__comment_isset)
  {
    [encoder encodeObject: __comment forKey: @"comment"];
  }
}

- (void) dealloc
{
  [__comment release_stub];
  [super dealloc_stub];
}

- (int32_t) num1 {
  return __num1;
}

- (void) setNum1: (int32_t) num1 {
  __num1 = num1;
  __num1_isset = YES;
}

- (BOOL) num1IsSet {
  return __num1_isset;
}

- (void) unsetNum1 {
  __num1_isset = NO;
}

- (int32_t) num2 {
  return __num2;
}

- (void) setNum2: (int32_t) num2 {
  __num2 = num2;
  __num2_isset = YES;
}

- (BOOL) num2IsSet {
  return __num2_isset;
}

- (void) unsetNum2 {
  __num2_isset = NO;
}

- (int) op {
  return __op;
}

- (void) setOp: (int) op {
  __op = op;
  __op_isset = YES;
}

- (BOOL) opIsSet {
  return __op_isset;
}

- (void) unsetOp {
  __op_isset = NO;
}

- (NSString *) comment {
  return [[__comment retain_stub] autorelease_stub];
}

- (void) setComment: (NSString *) comment {
  [comment retain_stub];
  [__comment release_stub];
  __comment = comment;
  __comment_isset = YES;
}

- (BOOL) commentIsSet {
  return __comment_isset;
}

- (void) unsetComment {
  [__comment release_stub];
  __comment = nil;
  __comment_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setNum1: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setNum2: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_I32) {
          int fieldValue = [inProtocol readI32];
          [self setOp: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setComment: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"Work"];
  if (__num1_isset) {
    [outProtocol writeFieldBeginWithName: @"num1" type: TType_I32 fieldID: 1];
    [outProtocol writeI32: __num1];
    [outProtocol writeFieldEnd];
  }
  if (__num2_isset) {
    [outProtocol writeFieldBeginWithName: @"num2" type: TType_I32 fieldID: 2];
    [outProtocol writeI32: __num2];
    [outProtocol writeFieldEnd];
  }
  if (__op_isset) {
    [outProtocol writeFieldBeginWithName: @"op" type: TType_I32 fieldID: 3];
    [outProtocol writeI32: __op];
    [outProtocol writeFieldEnd];
  }
  if (__comment_isset) {
    if (__comment != nil) {
      [outProtocol writeFieldBeginWithName: @"comment" type: TType_STRING fieldID: 4];
      [outProtocol writeString: __comment];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"Work("];
  [ms appendString: @"num1:"];
  [ms appendFormat: @"%i", __num1];
  [ms appendString: @",num2:"];
  [ms appendFormat: @"%i", __num2];
  [ms appendString: @",op:"];
  [ms appendFormat: @"%i", __op];
  [ms appendString: @",comment:"];
  [ms appendFormat: @"\"%@\"", __comment];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation InvalidOperation

- (id) init
{
  return [super initWithName: @"InvalidOperation" reason: @"unknown" userInfo: nil];
}

- (id) initWithWhat: (int32_t) what why: (NSString *) why
{
  self = [self init];
  __what = what;
  __what_isset = YES;
  __why = [why retain_stub];
  __why_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super initWithCoder: decoder];
  if ([decoder containsValueForKey: @"what"])
  {
    __what = [decoder decodeInt32ForKey: @"what"];
    __what_isset = YES;
  }
  if ([decoder containsValueForKey: @"why"])
  {
    __why = [[decoder decodeObjectForKey: @"why"] retain_stub];
    __why_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  [super encodeWithCoder: encoder];
  if (__what_isset)
  {
    [encoder encodeInt32: __what forKey: @"what"];
  }
  if (__why_isset)
  {
    [encoder encodeObject: __why forKey: @"why"];
  }
}

- (void) dealloc
{
  [__why release_stub];
  [super dealloc_stub];
}

- (int32_t) what {
  return __what;
}

- (void) setWhat: (int32_t) what {
  __what = what;
  __what_isset = YES;
}

- (BOOL) whatIsSet {
  return __what_isset;
}

- (void) unsetWhat {
  __what_isset = NO;
}

- (NSString *) why {
  return [[__why retain_stub] autorelease_stub];
}

- (void) setWhy: (NSString *) why {
  [why retain_stub];
  [__why release_stub];
  __why = why;
  __why_isset = YES;
}

- (BOOL) whyIsSet {
  return __why_isset;
}

- (void) unsetWhy {
  [__why release_stub];
  __why = nil;
  __why_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setWhat: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setWhy: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"InvalidOperation"];
  if (__what_isset) {
    [outProtocol writeFieldBeginWithName: @"what" type: TType_I32 fieldID: 1];
    [outProtocol writeI32: __what];
    [outProtocol writeFieldEnd];
  }
  if (__why_isset) {
    if (__why != nil) {
      [outProtocol writeFieldBeginWithName: @"why" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __why];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"InvalidOperation("];
  [ms appendString: @"what:"];
  [ms appendFormat: @"%i", __what];
  [ms appendString: @",why:"];
  [ms appendFormat: @"\"%@\"", __why];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

static int32_t INT32CONSTANT = 9853;
static NSMutableDictionary * MAPCONSTANT;

@implementation helloConstants
+ (void) initialize {
  MAPCONSTANT = [[NSMutableDictionary alloc] initWithCapacity:2]; 
  [MAPCONSTANT setObject:@"world" forKey:@"hello"];
  [MAPCONSTANT setObject:@"moon" forKey:@"goodnight"];

;
}
+ (int32_t) INT32CONSTANT{
  return INT32CONSTANT;
}
+ (NSMutableDictionary *) MAPCONSTANT{
  return MAPCONSTANT;
}
@end

@interface ping_args : NSObject <TBase, NSCoding> {
}

- (id) init;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

@end

@implementation ping_args

- (id) init
{
  self = [super init];
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"ping_args"];
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"ping_args("];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface Ping_result : NSObject <TBase, NSCoding> {
}

- (id) init;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

@end

@implementation Ping_result

- (id) init
{
  self = [super init];
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"Ping_result"];

  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"Ping_result("];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface add_args : NSObject <TBase, NSCoding> {
  int32_t __num1;
  int32_t __num2;

  BOOL __num1_isset;
  BOOL __num2_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=num1, setter=setNum1:) int32_t num1;
@property (nonatomic, getter=num2, setter=setNum2:) int32_t num2;
#endif

- (id) init;
- (id) initWithNum1: (int32_t) num1 num2: (int32_t) num2;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) num1;
- (void) setNum1: (int32_t) num1;
#endif
- (BOOL) num1IsSet;

#if !__has_feature(objc_arc)
- (int32_t) num2;
- (void) setNum2: (int32_t) num2;
#endif
- (BOOL) num2IsSet;

@end

@implementation add_args

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithNum1: (int32_t) num1 num2: (int32_t) num2
{
  self = [super init];
  __num1 = num1;
  __num1_isset = YES;
  __num2 = num2;
  __num2_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"num1"])
  {
    __num1 = [decoder decodeInt32ForKey: @"num1"];
    __num1_isset = YES;
  }
  if ([decoder containsValueForKey: @"num2"])
  {
    __num2 = [decoder decodeInt32ForKey: @"num2"];
    __num2_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__num1_isset)
  {
    [encoder encodeInt32: __num1 forKey: @"num1"];
  }
  if (__num2_isset)
  {
    [encoder encodeInt32: __num2 forKey: @"num2"];
  }
}

- (void) dealloc
{
  [super dealloc_stub];
}

- (int32_t) num1 {
  return __num1;
}

- (void) setNum1: (int32_t) num1 {
  __num1 = num1;
  __num1_isset = YES;
}

- (BOOL) num1IsSet {
  return __num1_isset;
}

- (void) unsetNum1 {
  __num1_isset = NO;
}

- (int32_t) num2 {
  return __num2;
}

- (void) setNum2: (int32_t) num2 {
  __num2 = num2;
  __num2_isset = YES;
}

- (BOOL) num2IsSet {
  return __num2_isset;
}

- (void) unsetNum2 {
  __num2_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setNum1: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setNum2: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"add_args"];
  if (__num1_isset) {
    [outProtocol writeFieldBeginWithName: @"num1" type: TType_I32 fieldID: 1];
    [outProtocol writeI32: __num1];
    [outProtocol writeFieldEnd];
  }
  if (__num2_isset) {
    [outProtocol writeFieldBeginWithName: @"num2" type: TType_I32 fieldID: 2];
    [outProtocol writeI32: __num2];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"add_args("];
  [ms appendString: @"num1:"];
  [ms appendFormat: @"%i", __num1];
  [ms appendString: @",num2:"];
  [ms appendFormat: @"%i", __num2];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface Add_result : NSObject <TBase, NSCoding> {
  int32_t __success;

  BOOL __success_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=success, setter=setSuccess:) int32_t success;
#endif

- (id) init;
- (id) initWithSuccess: (int32_t) success;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) success;
- (void) setSuccess: (int32_t) success;
#endif
- (BOOL) successIsSet;

@end

@implementation Add_result

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithSuccess: (int32_t) success
{
  self = [super init];
  __success = success;
  __success_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"success"])
  {
    __success = [decoder decodeInt32ForKey: @"success"];
    __success_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__success_isset)
  {
    [encoder encodeInt32: __success forKey: @"success"];
  }
}

- (void) dealloc
{
  [super dealloc_stub];
}

- (int32_t) success {
  return __success;
}

- (void) setSuccess: (int32_t) success {
  __success = success;
  __success_isset = YES;
}

- (BOOL) successIsSet {
  return __success_isset;
}

- (void) unsetSuccess {
  __success_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 0:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setSuccess: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"Add_result"];

  if (__success_isset) {
    [outProtocol writeFieldBeginWithName: @"success" type: TType_I32 fieldID: 0];
    [outProtocol writeI32: __success];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"Add_result("];
  [ms appendString: @"success:"];
  [ms appendFormat: @"%i", __success];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface calculate_args : NSObject <TBase, NSCoding> {
  int32_t __logid;
  Work * __w;

  BOOL __logid_isset;
  BOOL __w_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=logid, setter=setLogid:) int32_t logid;
@property (nonatomic, retain, getter=w, setter=setW:) Work * w;
#endif

- (id) init;
- (id) initWithLogid: (int32_t) logid w: (Work *) w;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) logid;
- (void) setLogid: (int32_t) logid;
#endif
- (BOOL) logidIsSet;

#if !__has_feature(objc_arc)
- (Work *) w;
- (void) setW: (Work *) w;
#endif
- (BOOL) wIsSet;

@end

@implementation calculate_args

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithLogid: (int32_t) logid w: (Work *) w
{
  self = [super init];
  __logid = logid;
  __logid_isset = YES;
  __w = [w retain_stub];
  __w_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"logid"])
  {
    __logid = [decoder decodeInt32ForKey: @"logid"];
    __logid_isset = YES;
  }
  if ([decoder containsValueForKey: @"w"])
  {
    __w = [[decoder decodeObjectForKey: @"w"] retain_stub];
    __w_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__logid_isset)
  {
    [encoder encodeInt32: __logid forKey: @"logid"];
  }
  if (__w_isset)
  {
    [encoder encodeObject: __w forKey: @"w"];
  }
}

- (void) dealloc
{
  [__w release_stub];
  [super dealloc_stub];
}

- (int32_t) logid {
  return __logid;
}

- (void) setLogid: (int32_t) logid {
  __logid = logid;
  __logid_isset = YES;
}

- (BOOL) logidIsSet {
  return __logid_isset;
}

- (void) unsetLogid {
  __logid_isset = NO;
}

- (Work *) w {
  return [[__w retain_stub] autorelease_stub];
}

- (void) setW: (Work *) w {
  [w retain_stub];
  [__w release_stub];
  __w = w;
  __w_isset = YES;
}

- (BOOL) wIsSet {
  return __w_isset;
}

- (void) unsetW {
  [__w release_stub];
  __w = nil;
  __w_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setLogid: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRUCT) {
          Work *fieldValue = [[Work alloc] init];
          [fieldValue read: inProtocol];
          [self setW: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"calculate_args"];
  if (__logid_isset) {
    [outProtocol writeFieldBeginWithName: @"logid" type: TType_I32 fieldID: 1];
    [outProtocol writeI32: __logid];
    [outProtocol writeFieldEnd];
  }
  if (__w_isset) {
    if (__w != nil) {
      [outProtocol writeFieldBeginWithName: @"w" type: TType_STRUCT fieldID: 2];
      [__w write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"calculate_args("];
  [ms appendString: @"logid:"];
  [ms appendFormat: @"%i", __logid];
  [ms appendString: @",w:"];
  [ms appendFormat: @"%@", __w];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface Calculate_result : NSObject <TBase, NSCoding> {
  int32_t __success;
  InvalidOperation * __ouch;

  BOOL __success_isset;
  BOOL __ouch_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=success, setter=setSuccess:) int32_t success;
@property (nonatomic, retain, getter=ouch, setter=setOuch:) InvalidOperation * ouch;
#endif

- (id) init;
- (id) initWithSuccess: (int32_t) success ouch: (InvalidOperation *) ouch;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) success;
- (void) setSuccess: (int32_t) success;
#endif
- (BOOL) successIsSet;

#if !__has_feature(objc_arc)
- (InvalidOperation *) ouch;
- (void) setOuch: (InvalidOperation *) ouch;
#endif
- (BOOL) ouchIsSet;

@end

@implementation Calculate_result

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithSuccess: (int32_t) success ouch: (InvalidOperation *) ouch
{
  self = [super init];
  __success = success;
  __success_isset = YES;
  __ouch = [ouch retain_stub];
  __ouch_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"success"])
  {
    __success = [decoder decodeInt32ForKey: @"success"];
    __success_isset = YES;
  }
  if ([decoder containsValueForKey: @"ouch"])
  {
    __ouch = [[decoder decodeObjectForKey: @"ouch"] retain_stub];
    __ouch_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__success_isset)
  {
    [encoder encodeInt32: __success forKey: @"success"];
  }
  if (__ouch_isset)
  {
    [encoder encodeObject: __ouch forKey: @"ouch"];
  }
}

- (void) dealloc
{
  [__ouch release_stub];
  [super dealloc_stub];
}

- (int32_t) success {
  return __success;
}

- (void) setSuccess: (int32_t) success {
  __success = success;
  __success_isset = YES;
}

- (BOOL) successIsSet {
  return __success_isset;
}

- (void) unsetSuccess {
  __success_isset = NO;
}

- (InvalidOperation *) ouch {
  return [[__ouch retain_stub] autorelease_stub];
}

- (void) setOuch: (InvalidOperation *) ouch {
  [ouch retain_stub];
  [__ouch release_stub];
  __ouch = ouch;
  __ouch_isset = YES;
}

- (BOOL) ouchIsSet {
  return __ouch_isset;
}

- (void) unsetOuch {
  [__ouch release_stub];
  __ouch = nil;
  __ouch_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 0:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setSuccess: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 1:
        if (fieldType == TType_STRUCT) {
          InvalidOperation *fieldValue = [[InvalidOperation alloc] init];
          [fieldValue read: inProtocol];
          [self setOuch: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"Calculate_result"];

  if (__success_isset) {
    [outProtocol writeFieldBeginWithName: @"success" type: TType_I32 fieldID: 0];
    [outProtocol writeI32: __success];
    [outProtocol writeFieldEnd];
  } else if (__ouch_isset) {
    if (__ouch != nil) {
      [outProtocol writeFieldBeginWithName: @"ouch" type: TType_STRUCT fieldID: 1];
      [__ouch write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"Calculate_result("];
  [ms appendString: @"success:"];
  [ms appendFormat: @"%i", __success];
  [ms appendString: @",ouch:"];
  [ms appendFormat: @"%@", __ouch];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface zip_args : NSObject <TBase, NSCoding> {
}

- (id) init;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

@end

@implementation zip_args

- (id) init
{
  self = [super init];
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"zip_args"];
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"zip_args("];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation CalculatorClient
- (id) initWithProtocol: (id <TProtocol>) protocol
{
  return [self initWithInProtocol: protocol outProtocol: protocol];
}

- (id) initWithInProtocol: (id <TProtocol>) anInProtocol outProtocol: (id <TProtocol>) anOutProtocol
{
  self = [super init];
  inProtocol = [anInProtocol retain_stub];
  outProtocol = [anOutProtocol retain_stub];
  return self;
}

- (void) dealloc
{
  [inProtocol release_stub];
  [outProtocol release_stub];
  [super dealloc_stub];
}

- (void) send_ping
{
  [outProtocol writeMessageBeginWithName: @"ping" type: TMessageType_CALL sequenceID: 0];
  [outProtocol writeStructBeginWithName: @"ping_args"];
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
}

- (void) recv_ping
{
  int msgType = 0;
  [inProtocol readMessageBeginReturningName: nil type: &msgType sequenceID: NULL];
  if (msgType == TMessageType_EXCEPTION) {
    TApplicationException * x = [TApplicationException read: inProtocol];
    [inProtocol readMessageEnd];
    @throw x;
  }
  Ping_result * result = [[[Ping_result alloc] init] autorelease_stub];
  [result read: inProtocol];
  [inProtocol readMessageEnd];
  return;
}

- (void) ping
{
  [self send_ping];
  [self recv_ping];
}

- (void) send_add: (int32_t) num1 num2: (int32_t) num2
{
  [outProtocol writeMessageBeginWithName: @"add" type: TMessageType_CALL sequenceID: 0];
  [outProtocol writeStructBeginWithName: @"add_args"];
  [outProtocol writeFieldBeginWithName: @"num1" type: TType_I32 fieldID: 1];
  [outProtocol writeI32: num1];
  [outProtocol writeFieldEnd];
  [outProtocol writeFieldBeginWithName: @"num2" type: TType_I32 fieldID: 2];
  [outProtocol writeI32: num2];
  [outProtocol writeFieldEnd];
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
}

- (int32_t) recv_add
{
  int msgType = 0;
  [inProtocol readMessageBeginReturningName: nil type: &msgType sequenceID: NULL];
  if (msgType == TMessageType_EXCEPTION) {
    TApplicationException * x = [TApplicationException read: inProtocol];
    [inProtocol readMessageEnd];
    @throw x;
  }
  Add_result * result = [[[Add_result alloc] init] autorelease_stub];
  [result read: inProtocol];
  [inProtocol readMessageEnd];
  if ([result successIsSet]) {
    return [result success];
  }
  @throw [TApplicationException exceptionWithType: TApplicationException_MISSING_RESULT
                                           reason: @"add failed: unknown result"];
}

- (int32_t) add: (int32_t) num1 num2: (int32_t) num2
{
  [self send_add : num1 num2: num2];
  return [self recv_add];
}

- (void) send_calculate: (int32_t) logid w: (Work *) w
{
  [outProtocol writeMessageBeginWithName: @"calculate" type: TMessageType_CALL sequenceID: 0];
  [outProtocol writeStructBeginWithName: @"calculate_args"];
  [outProtocol writeFieldBeginWithName: @"logid" type: TType_I32 fieldID: 1];
  [outProtocol writeI32: logid];
  [outProtocol writeFieldEnd];
  if (w != nil)  {
    [outProtocol writeFieldBeginWithName: @"w" type: TType_STRUCT fieldID: 2];
    [w write: outProtocol];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
}

- (int32_t) recv_calculate
{
  int msgType = 0;
  [inProtocol readMessageBeginReturningName: nil type: &msgType sequenceID: NULL];
  if (msgType == TMessageType_EXCEPTION) {
    TApplicationException * x = [TApplicationException read: inProtocol];
    [inProtocol readMessageEnd];
    @throw x;
  }
  Calculate_result * result = [[[Calculate_result alloc] init] autorelease_stub];
  [result read: inProtocol];
  [inProtocol readMessageEnd];
  if ([result successIsSet]) {
    return [result success];
  }
  if ([result ouchIsSet]) {
    @throw [result ouch];
  }
  @throw [TApplicationException exceptionWithType: TApplicationException_MISSING_RESULT
                                           reason: @"calculate failed: unknown result"];
}

- (int32_t) calculate: (int32_t) logid w: (Work *) w
{
  [self send_calculate : logid w: w];
  return [self recv_calculate];
}

- (void) send_zip
{
  [outProtocol writeMessageBeginWithName: @"zip" type: TMessageType_CALL sequenceID: 0];
  [outProtocol writeStructBeginWithName: @"zip_args"];
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
}

- (void) zip
{
  [self send_zip];
}

@end

@implementation CalculatorProcessor

- (id) initWithCalculator: (id <Calculator>) service
{
  self = [super init];
  if (!self) {
    return nil;
  }
  mService = [service retain_stub];
  mMethodMap = [[NSMutableDictionary dictionary] retain_stub];
  {
    SEL s = @selector(process_ping_withSequenceID:inProtocol:outProtocol:);
    NSMethodSignature * sig = [self methodSignatureForSelector: s];
    NSInvocation * invocation = [NSInvocation invocationWithMethodSignature: sig];
    [invocation setSelector: s];
    [invocation retainArguments];
    [mMethodMap setValue: invocation forKey: @"ping"];
  }
  {
    SEL s = @selector(process_add_withSequenceID:inProtocol:outProtocol:);
    NSMethodSignature * sig = [self methodSignatureForSelector: s];
    NSInvocation * invocation = [NSInvocation invocationWithMethodSignature: sig];
    [invocation setSelector: s];
    [invocation retainArguments];
    [mMethodMap setValue: invocation forKey: @"add"];
  }
  {
    SEL s = @selector(process_calculate_withSequenceID:inProtocol:outProtocol:);
    NSMethodSignature * sig = [self methodSignatureForSelector: s];
    NSInvocation * invocation = [NSInvocation invocationWithMethodSignature: sig];
    [invocation setSelector: s];
    [invocation retainArguments];
    [mMethodMap setValue: invocation forKey: @"calculate"];
  }
  {
    SEL s = @selector(process_zip_withSequenceID:inProtocol:outProtocol:);
    NSMethodSignature * sig = [self methodSignatureForSelector: s];
    NSInvocation * invocation = [NSInvocation invocationWithMethodSignature: sig];
    [invocation setSelector: s];
    [invocation retainArguments];
    [mMethodMap setValue: invocation forKey: @"zip"];
  }
  return self;
}

- (id<Calculator>) service
{
  return [[mService retain_stub] autorelease_stub];
}

- (BOOL) processOnInputProtocol: (id <TProtocol>) inProtocol
                 outputProtocol: (id <TProtocol>) outProtocol
{
  NSString * messageName;
  int messageType;
  int seqID;
  [inProtocol readMessageBeginReturningName: &messageName
                                       type: &messageType
                                 sequenceID: &seqID];
  NSInvocation * invocation = [mMethodMap valueForKey: messageName];
  if (invocation == nil) {
    [TProtocolUtil skipType: TType_STRUCT onProtocol: inProtocol];
    [inProtocol readMessageEnd];
    TApplicationException * x = [TApplicationException exceptionWithType: TApplicationException_UNKNOWN_METHOD reason: [NSString stringWithFormat: @"Invalid method name: '%@'", messageName]];
    [outProtocol writeMessageBeginWithName: messageName
                                      type: TMessageType_EXCEPTION
                                sequenceID: seqID];
    [x write: outProtocol];
    [outProtocol writeMessageEnd];
    [[outProtocol transport] flush];
    return YES;
  }
  // NSInvocation does not conform to NSCopying protocol
  NSInvocation * i = [NSInvocation invocationWithMethodSignature: [invocation methodSignature]];
  [i setSelector: [invocation selector]];
  [i setArgument: &seqID atIndex: 2];
  [i setArgument: &inProtocol atIndex: 3];
  [i setArgument: &outProtocol atIndex: 4];
  [i setTarget: self];
  [i invoke];
  return YES;
}

- (void) process_ping_withSequenceID: (int32_t) seqID inProtocol: (id<TProtocol>) inProtocol outProtocol: (id<TProtocol>) outProtocol
{
  ping_args * args = [[ping_args alloc] init];
  [args read: inProtocol];
  [inProtocol readMessageEnd];
  Ping_result * result = [[Ping_result alloc] init];
  [mService ping];
  [outProtocol writeMessageBeginWithName: @"ping"
                                    type: TMessageType_REPLY
                              sequenceID: seqID];
  [result write: outProtocol];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
  [result release_stub];
  [args release_stub];
}

- (void) process_add_withSequenceID: (int32_t) seqID inProtocol: (id<TProtocol>) inProtocol outProtocol: (id<TProtocol>) outProtocol
{
  add_args * args = [[add_args alloc] init];
  [args read: inProtocol];
  [inProtocol readMessageEnd];
  Add_result * result = [[Add_result alloc] init];
  [result setSuccess: [mService add: [args num1] num2: [args num2]]];
  [outProtocol writeMessageBeginWithName: @"add"
                                    type: TMessageType_REPLY
                              sequenceID: seqID];
  [result write: outProtocol];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
  [result release_stub];
  [args release_stub];
}

- (void) process_calculate_withSequenceID: (int32_t) seqID inProtocol: (id<TProtocol>) inProtocol outProtocol: (id<TProtocol>) outProtocol
{
  calculate_args * args = [[calculate_args alloc] init];
  [args read: inProtocol];
  [inProtocol readMessageEnd];
  Calculate_result * result = [[Calculate_result alloc] init];
  [result setSuccess: [mService calculate: [args logid] w: [args w]]];
  [outProtocol writeMessageBeginWithName: @"calculate"
                                    type: TMessageType_REPLY
                              sequenceID: seqID];
  [result write: outProtocol];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
  [result release_stub];
  [args release_stub];
}

- (void) process_zip_withSequenceID: (int32_t) seqID inProtocol: (id<TProtocol>) inProtocol outProtocol: (id<TProtocol>) outProtocol
{
  zip_args * args = [[zip_args alloc] init];
  [args read: inProtocol];
  [inProtocol readMessageEnd];
  [mService zip];
  [args release_stub];
}

- (void) dealloc
{
  [mService release_stub];
  [mMethodMap release_stub];
  [super dealloc_stub];
}

@end

