/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "hello_constants.h"

namespace uzzu { namespace thrift { namespace tutorial {

const helloConstants g_hello_constants;

helloConstants::helloConstants() {
  INT32CONSTANT = 9853;

  MAPCONSTANT.insert(std::make_pair("hello", "world"));
  MAPCONSTANT.insert(std::make_pair("goodnight", "moon"));

}

}}} // namespace

