/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef hello_CONSTANTS_H
#define hello_CONSTANTS_H

#include "hello_types.h"

namespace uzzu { namespace thrift { namespace tutorial {

class helloConstants {
 public:
  helloConstants();

  int32_t INT32CONSTANT;
  std::map<std::string, std::string>  MAPCONSTANT;
};

extern const helloConstants g_hello_constants;

}}} // namespace

#endif
